### ISSUE TITLE
Make text in "Remove Liquidity" pretty

### ISSUE THREAD

**Issue by daveaneo** [Blockchain-Solutions-LLC/Quarrychain-dApp#77]
Default text: "Please select your LP tokens from "Your Liquidity" 
Please style this (no guide--use your best intuition)

**Comment by nestorolivaresh** [comment]
@daveaneo and I decide it to make the "Remove Liquidity" tab button not clickable but visible for user's reference.

**Comment by nestorolivaresh** [comment]
Fixed here: https://github.com/Blockchain-Solutions-LLC/Quarrychain-dApp/pull/83. Confirmed by @daveaneo.
